### ISSUE TITLE
Deploy in a Quasar framework app

### ISSUE THREAD

**Issue by diegomagikal** [xon52/x5-gmaps#26]
Thanks a lot for this project!

I'm trying to run x5-gmaps in a Quasar app:

```
import { gmapsMap, gmapsMarker } from 'x5-gmaps'
export default {
  components: { gmapsMap, gmapsMarker },
}
```

```
<template>
  <gmaps-map>
    <gmaps-marker :position="{ lat: -27, lng: 153 }" />
  </gmaps-map>
</template>
```

```
import Vue from 'vue'
Vue.use(gmapsMap, { key: 'XXXXXXX, libraries: ['places'] })
```
But I get this error:

`Error in mounted hook: "TypeError: this.$GMaps is not a function"`

I'm already tried to create `this.$GMaps` manually putting the following code in a `quasar boot` file:

```
//file /src/boot/gmaps.js
import { gmapsMap } from 'x5-gmaps'
export default ({ app, router, Vue }) => {
  Vue.prototype.$GMaps = gmapsMap
  Vue.use(gmapsMap, { key: 'XXXXX', libraries: ['places'] })
}
```

But the same error occurs. Any idea? Thanks in advance!

**Comment by xon52** [comment]
Hi @diegomagikal, thanks for raising this issue. TBH, I don't have much experience (none at all) with Quasar, so I can't comment on that specifically; however, after reading this I had another idea to avoid the potential context issues `this.$GMaps` will have.

Please try the latest version (0.3.30) as I have added an additional way to access the Google Maps API (instead of `this.$GMaps`); by allowing you to import that function (that returns a promise) from the package like a component.

```js
import { gmaps } from 'x5-gmaps'
...
```

Please see if that changes anything, and if there is still a problem, try find a way to replicate it so I can try help solve it.

**Comment by diegomagikal** [comment]
Hello, thanks for your help.

After upgrade to 0.3.30, the `this.$GMaps` error is gone, but I can't still initiate the plugin. I get the error `TypeError: Cannot read property 'install' of undefined`.

You can check it here:
https://codesandbox.io/s/clever-dewdney-c535r?file=/src/boot/gmaps.js

Or:
https://github.com/diegomagikal/x5-gmaps-issue-26

Note: the files are `/src/boot/gmaps.js` and `/src/pages/Index.vue`

**Comment by xon52** [comment]
OK, so after a bit of learning: [Quasar is special](https://techformist.com/using-vue-plugins-quasar/) when is comes to plugins which I didn't realise. I'll need to add it in the docs, but you can't use my installation instructions of `Vue.use(x5Gmaps, 'XXXX')`. What you need to do instead is in your `gmaps.js` boot file, import the default export as 'install' and run that with the Vue instance and options as the parameters:

```js
import { default as install } from "x5-gmaps";

export default async ({ Vue }) => {
  install(Vue, { key: "XXXXXX", libraries: ["places"] });
};
```

That should fix your problem.

There is another issue that I noticed with your usage though:
1. In your `Index.vue` file, you are importing `x5GMaps` which is not a thing - that should be `gmapsMap`
2. Your components object includes `gmaps` which is not a component, but the Google Maps API promise.

So it should be:

```js
import { gmapsMap, gmapsMarker, gmaps } from 'x5-gmaps'
import Vue from 'vue'

export default {
  components: { gmapsMap, gmapsMarker },
  mounted () {
    gmaps().then((response) => {
...
```

**Comment by diegomagikal** [comment]
Great! Thank you very much. It's working perfectly. I'm migrating a legacy web app to Vue so your plugin will be very useful for me. Cheers!
